name: 'Issue States'

on:
  project_v2_item:
    types: reordered

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v3
        with:
          closed-issue-columns: 'Done'
