name: Comment on PR

on:
  pull_request:
    types:
      - opened
    

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.base.repo.name == 'workflow-testing'
    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Your branch is: ${{ steps.extract_branch.outputs.branch }}
