name: Delete folder

on: delete

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    env:
      FULL_BRANCH_NAME: ${{ github.event.ref }}
    steps:
      - name: Extract branch name
        run: echo "branch=${FULL_BRANCH_NAME#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.DELETE_FOLDER_APP_ID }}
          private_key: ${{ secrets.DELETE_FOLDER_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gchq-dev-741-test-org/test-repo
          token: ${{ steps.generate_token.outputs.token }}

      - name: Remove and commit
        uses: EndBug/add-and-commit@v9.1.1
        if: ${{ steps.extract_branch.outputs.branch != '' }}
        with:
          default_author: github_actions
          add: ""
          remove: ./branches/${{ steps.extract_branch.outputs.branch }} -r
          message: |
            Branch: ${{ steps.extract_branch.outputs.branch }} deleted from repo
