name: Delete folder

on: delete

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    env:
      FULL_BRANCH_NAME: ${{ github.event.ref }}
    steps:
      - name: Extract branch name
        run: echo "branch=${FULL_BRANCH_NAME#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: GCHQ-Developer-741/test-repo
          persist-credentials: false
          fetch-depth: 0

      - name: Remove and commit
        uses: EndBug/add-and-commit@v9.1.1
        if: ${{ steps.extract_branch.outputs.branch != '' }}
        with:
          default_author: github_actions
          add: ""
          remove: ./branches/${{ steps.extract_branch.outputs.branch }} -r
          message: |
            Branch: ${{ steps.extract_branch.outputs.branch }} deleted from repo
