name: Delete folder

on: delete

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Extract branch name
        run: echo "branch=${github.event.ref#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Remove and commit
        uses: EndBug/add-and-commit@v9.1.1
        if: ${{ steps.extract_branch.outputs.branch != '' }}
        with:
          add: ""
          remove: ./branches/${{ steps.extract_branch.outputs.branch }}
          push: false
          message: |
            Branch: ${{ steps.extract_branch.outputs.branch }} deleted from repo
