name: Welcome new contributors to the repo

on:
  pull_request_target:
    types:
      - opened

jobs:
  welcome-message:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != 'gchq-dev-741-test-org/workflow-testing'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          pr-message: |
            # Welcome 👋
